package pa4;

/**
 ######################################################
 #################### by Shu Liu ######################
 ############ shutel at hotmail dot com ###############
 ################### 04/12/2016 #######################
 ########### GenText project @ USC CSCI455 ############
 ######################################################
 */

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *This class is in charge of writing all generated words to the output File one by one
 */
public class Output {
	private final int MAX_LENGTH = 80;
	private int length = 0;
	
	/**
	 * Write all generated words to the output File one by one
	 * @param wordGen the word generated by Markov process
	 * @param outFileName the name of output file
	 * @throws IOException deal with exceptions of output files
	 */
	public void fileWrite(String wordGen, String outFileName) throws IOException{
		try{
			File outFile = new File(outFileName);
			outFile.createNewFile();
			FileWriter fileWriter = new FileWriter(outFile, true);
			
		if(length == 0){
			fileWriter.write(wordGen);
			length = wordGen.length();
		}
		
		else{
			length = length + 1 + wordGen.length();
		if(length <= MAX_LENGTH){
			fileWriter.write(" " + wordGen);
		}
		if(length > MAX_LENGTH){
			fileWriter.write("\n" + wordGen);
			length = wordGen.length();
		}
		}
		fileWriter.close();
		}
		catch(IOException e){
			e.printStackTrace();
		}
	}
	
}
